=== nimakarimipour/opencms-core/src/org/opencms/configuration/opencms-sites.dtd
<!--
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (sites)>

<!--
# Configuration that controls individual sites in OpenCms.
# Each <site> sub-node of <sites> defines a site with the server name
# and the corresponding VFS-URI in OpenCms.
#
# workplace-server: the default server of the OpenCms workplace
# default-uri:      the default uri marks the site that is used when a request matches no defined site
# shared-folder:    the uri used for the shared folder, default="/shared/"
# site:             a site
#     server:       the server address used for the site
#     uri:          the absolute VFS path used for the site
#     title:        optional display title
#     position:     optional position for display order
#     errorPage:    absolute URI to an error page used for this site (optional)
#     webserver:    if set to true, a web-server configuration can be generated for this site
#     subsiteSelection: when true, quick selection for subsites will be enabled 
# secure:           an optional secure server for the site:
#     server:       the server address used for this site
#     exclusive:    if set to true, secure resources will only be available using the given secure url
#                   do not forget to configure an additional tomcat connector using
#                   proxyPort="443" scheme="https" secure="false"
#     error:        if exclusive, and set to true will generate a 404 error, if set to false will redirect to secure url
# alias:            alias servers for the site
#     server:       the server address used for this site
#     offset:       time in seconds added to the current time written as attribute
#                   into the session when accessing the site over this alias
#     redirect:     Possible values: true, false, permanent. If true or permanent, redirect to main URL with HTTP status 302 or 301, respectively.
# 
#alternative-site-root: alternative site root to use for specific paths - can be separately selected in the site selector
#	uri:			the alternative site root path
#	title-suffix:	the title suffix to display for the alternative site root in the site selector
#	path (element):	a path prefix for which the alternative site root should be used  
#
-->
<!ELEMENT sites ((workplace-server+, default-uri, shared-folder?,oldStyleSecureServer?, webserver-scripting?, site+) | (workplace-server+, default-uri, oldStyleSecureServer?,webserver-scripting?, site+, shared-folder?))>
<!ELEMENT workplace-server (#PCDATA)>
<!ATTLIST workplace-server
	sslmode (no|manual|manual-ep-termination|lets-encrypt) "no">
<!ELEMENT default-uri (#PCDATA)>
<!ELEMENT oldStyleSecureServer (#PCDATA)>
<!ELEMENT webserver-scripting (webserverscript, targetpath, configtemplate,securetemplate, filenameprefix, loggingdir)>
<!ELEMENT webserverscript (#PCDATA)>
<!ELEMENT targetpath (#PCDATA)>
<!ELEMENT configtemplate (#PCDATA)>
<!ELEMENT securetemplate (#PCDATA)>
<!ELEMENT filenameprefix (#PCDATA)>
<!ELEMENT loggingdir (#PCDATA)>
<!ELEMENT shared-folder (#PCDATA)>
<!ELEMENT site (secure?, parameters?, alias*, alternative-site-root?)>
<!ATTLIST site
	server CDATA #REQUIRED
	uri CDATA #REQUIRED
	title CDATA #IMPLIED
	position CDATA #IMPLIED
	errorPage CDATA #IMPLIED
	subsiteSelection CDATA #IMPLIED
	webserver (true|false|TRUE|FALSE) "true"
	sslmode (no|manual|manual-ep-termination|lets-encrypt|secure-server) "secure-server">
<!ELEMENT secure EMPTY>
<!ATTLIST secure
	server CDATA #REQUIRED
	exclusive (true|false|TRUE|FALSE) "false"
	error (true|false|TRUE|FALSE) "false"
	usePermanentRedirects (true|false|TRUE|FALSE) "false" 
	>
<!ELEMENT parameters (param*)>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>

<!ELEMENT alias EMPTY>	
<!ATTLIST alias
	server CDATA #REQUIRED
	redirect (true|false|True|False|permanent|Permanent) "false"
	offset CDATA #IMPLIED>
	
	
<!ELEMENT alternative-site-root (path*)>
<!ATTLIST alternative-site-root
	uri CDATA #REQUIRED
	title-suffix CDATA #REQUIRED>

<!ELEMENT path (#PCDATA)>

=== nimakarimipour/opencms-core/test/data/WEB-INF/config.de/opencms-sites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-sites.dtd">

<opencms>
	<sites>
		<workplace-server>http://localhost:8080</workplace-server>
		<default-uri>/sites/default/</default-uri>
		<shared-folder>/shared/</shared-folder>
		<site server="http://localhost:8080" uri="/sites/default/">
			<secure server="https://localhost:443" />
		</site>
		<site server="http://localhost:8081" uri="/sites/default/folder1/" />
		<site server="http://localhost:8082" uri="/sites/testsite/" />
	</sites>
</opencms>

=== nimakarimipour/opencms-core/test/org/opencms/configuration/opencms-sites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-sites.dtd">

<opencms>
	<sites>
		<workplace-server sslmode="no">http://localhost:8080</workplace-server>
		<default-uri>/sites/default/</default-uri>
		<oldStyleSecureServer>true</oldStyleSecureServer>
		<site server="http://localhost:8080" uri="/sites/default/" position="10.0" webserver="true" sslmode="secure-server" subsiteSelection="true">
			<secure server="http://www.mysecureserver.com" exclusive="true" error="true"/>	
            <parameters>
            	<param name="test1">test1</param>
              	<param name="test2">test2</param>
            </parameters> 	
            <alias server="http://www.aliasserver.com" redirect="false"/>              			
            <alias server="http://www.yetanotheraliasserver.com" redirect="false"/>			
		</site>
        <site server="http://other.localhost:8080" uri="/sites/other/" position="10.0" webserver="true" sslmode="secure-server" subsiteSelection="true">
            <alias server="http://blah.localhost:8080" redirect="false" offset="500"  />
            <alias server="http://temporary.localhost:8080" redirect="true"  />
            <alias server="http://permanent.localhost:8080" redirect="permanent"  />
            <alternative-site-root uri="/sites/foobar" title-suffix="alternative">
                <path>/foobar-folder1</path>
                <path>/foobar-folder2</path>
            </alternative-site-root>
        </site>
	</sites>
</opencms>

=== nimakarimipour/opencms-core/test/data/localizationConfig/opencms-sites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-sites.dtd">

<opencms>
	<sites>
		<workplace-server>http://localhost:8080</workplace-server>
		<default-uri>/sites/default/</default-uri>
		<shared-folder>/shared/</shared-folder>
		<site server="http://localhost:8080" uri="/sites/default/">
			<secure server="https://localhost:443" />
			<parameters>
				<param name="localizationMode">singleTree</param>
			</parameters>
		</site>
		<!-- If you add sites here, you also need to change the number of expected 
			sites in TestCmsSiteConfiguration. -->
		<site server="http://localhost:8081" uri="/sites/default/folder1/" />
		<site server="http://localhost:8082" uri="/sites/testsite/" />
		<site server="http://foo.org" uri="/sites/foo/" />
		<site server="http://bar.org" uri="/sites/bar/" />
	</sites>
</opencms>
