=== nimakarimipour/opencms-core/src/org/opencms/configuration/opencms-scheduler.dtd
<!--
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (scheduler)>

<!--
# Scheduler settings:
# The scheduler settings provide information for the OpenCms scheduler.
# The OpenCms scheduler is comparable with the CRON facility in Unix systems.
#
# The scheduler has a list of <job> subnodes.
# Most important for a job is the <class> name to be executed,
# and the <cronexpression> that controls the excution time.
-->

<!ELEMENT scheduler (job*)>

<!ELEMENT job (name?, class, reuseinstance?, active?, cronexpression, context, parameters?)>

<!--
# The job name is optional and used for information purposes only (e.g. in the log file).
# If no job name is provided, the class name is used as the job name.
-->
<!ELEMENT name (#PCDATA)>

<!--
# The job class name to execute at the scheduled time.
# This class _must_ implement the org.opencms.scheduler.I_CmsSchedulerJob interface.
-->
<!ELEMENT class (#PCDATA)>

<!--
# Optional configuration that controls if a new instance of the job class is created
# every time the job is run, or if an instance is created only for the first time and
# re-used for every later job execution.
#
# The #PCDATA value will be evaluated with Boolean.valueOf(#PCDATA).booleanValue().
# If the result is "true", the class instance will be re-used.
-->
<!ELEMENT reuseinstance (#PCDATA)>

<!--
# Optional configuration that controls if the job is active or not. If a job is not
# active, it is still kept in the job list, but not executed. This is intended for
# jobs that are frequently but not always used.
#
# The #PCDATA value will be evaluated with Boolean.valueOf(#PCDATA).booleanValue().
# If the result is "true", the class instance will be re-used.
-->
<!ELEMENT active (#PCDATA)>

<!--
# The cron expression to use for the job schedule.
# Please refer to the JavaDoc of the class org.opencms.scheduler.CmsScheduledJob
# for a full description of the possible options.
-->
<!ELEMENT cronexpression (#PCDATA)>

<!--
# Each job will be provided with an initialized instance of a CmsObject.
# The settings in the <context> node control the request context settings of this object.
#
# The defaults for the optional elements are:
# siteroot:   /
# requesturi: /
# locale:     the first locale configured as default locale
# encoding:   the configures system encoding
# remoteaddr: 127.0.0.1
-->
<!ELEMENT context (user, project, siteroot?, requesteduri?, locale?, encoding?, remoteaddr?)>

<!ELEMENT user (#PCDATA)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT siteroot (#PCDATA)>
<!ELEMENT requesteduri (#PCDATA)>
<!ELEMENT locale (#PCDATA)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT remoteaddr (#PCDATA)>

<!--
Each job can have an optional list of parameters.
-->

<!ELEMENT parameters (param*)>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>

=== nimakarimipour/opencms-core/test/org/opencms/configuration/opencms-scheduler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-scheduler.dtd">

<opencms>
	<scheduler>
		<job>
				<name>Test job name</name>
				<class>org.opencms.scheduler.TestScheduledJob</class>
				<reuseinstance>false</reuseinstance>
				<active>true</active>
				<cronexpression><![CDATA[0/2 * * * * ?]]></cronexpression>
				<context>
					<user>Admin</user>
					<project>Offline</project>
					<siteroot>/sites/default</siteroot>
					<requesteduri>/index.html</requesteduri>
					<locale>en</locale>
					<encoding>UTF-8</encoding>
					<remoteaddr>127.0.0.1</remoteaddr>
				</context>
				<parameters>
					<param name="param1">value1</param>
					<param name="param2">value2</param>
				</parameters>
			</job>		
			<job>
				<name>Another job name</name>
				<class>org.opencms.scheduler.TestScheduledJob</class>
				<reuseinstance>true</reuseinstance>
				<active>false</active>
				<cronexpression><![CDATA[0/10 * * * * ?]]></cronexpression>
				<context>
					<user>Admin</user>
					<project>Offline</project>
					<siteroot>/sites/default</siteroot>
					<requesteduri>/index.html</requesteduri>
					<locale>en</locale>
					<encoding>UTF-8</encoding>
					<remoteaddr>127.0.0.1</remoteaddr>
				</context>
			</job>			
	</scheduler>
</opencms>
