=== nimakarimipour/opencms-core/src/org/opencms/xml/page/xmlpage.dtd
<!ELEMENT page (elements)>
<!ELEMENT elements (element+)>	
<!ELEMENT element (links, content)>	
   <!ATTLIST element name CDATA #REQUIRED>
   <!ATTLIST element language CDATA #REQUIRED>
   <!ATTLIST element enabled (true|false) #IMPLIED>
<!ELEMENT links (link*)>	
<!ELEMENT link (target, uuid?, anchor?, query?)>	
   <!ATTLIST link name CDATA #REQUIRED>
   <!ATTLIST link internal (true|false) #REQUIRED>
   <!ATTLIST link type (A|IMG|OBJECT) #REQUIRED>
<!ELEMENT uuid (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT anchor (#PCDATA)>
<!ELEMENT query (#PCDATA)>
<!ELEMENT content (#PCDATA)>

=== nimakarimipour/opencms-core/test/org/opencms/xml/page/xmlpage-old-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "http://www.opencms.org/dtd/6.0/xmlpage.dtd">

<page>
	<elements>
		<element name="body" language="en">
			<links>
				<link name="link0" type="IMG" internal="true">
					<target><![CDATA[/sites/default/folder1/image2.gif]]></target>
				</link>
			</links>
			<content><![CDATA[English! Image <img src="${link0}" />]]></content>
		</element>
	</elements>
</page>
